<?php

$output .= '<h2><a class="show" label="2" onclick="return false;" href="#">'.__('Address', 'kwm_info_basic').'</a></h2>';
$output .= '<table class="form-table hidden 2 table table-bordered table-striped" id="contact">';
	$output .= '<tbody>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="address">'.__('Address', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][address]" id="address" maxlength="16" value="' . $kwm_info_options['address']['address']['address'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="number">'.__('Number', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][number]" id="number" maxlength="16" value="' . $kwm_info_options['address']['address']['number'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="neighborhood">'.__('Neighborhood', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][neighborhood]" id="neighborhood" maxlength="16" value="' . $kwm_info_options['address']['address']['neighborhood'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="complement">'.__('Complement', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][complement]" id="complement" maxlength="16" value="' . $kwm_info_options['address']['address']['complement'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="zipcode">'.__('Zip code', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][zipcode]" id="zipcode" maxlength="16" value="' . $kwm_info_options['address']['address']['zipcode'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';	
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="state">'.__('State', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][state]" id="state" maxlength="16" value="' . $kwm_info_options['address']['address']['state'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';		
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Instagram">'.__('Country', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="address[address][contry]" id="contry" maxlength="16" value="' . $kwm_info_options['address']['address']['contry'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';			
	$output .= '</tbody>';
$output .= '</table>';
?>