<?php
$output .= '<h2><a class="show" label="3" onclick="return false;" href="#">'. __('Social Network', 'kwm_info_basic') . '</a></h2>';
$output .= '<table class="form-table hidden 3 table table-bordered table-striped" id="contact">';
	$output .= '<tbody>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="facebook">facebook</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[facebook]" id="facebook" maxlength="16" value="' . $kwm_info_options['socialNetwork']['facebook'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="youtube">youtube</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[youtube]" id="youtube" maxlength="16" value="' . $kwm_info_options['socialNetwork']['youtube'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Twitter">Twitter</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[twitter]" id="twitter" maxlength="16" value="' . $kwm_info_options['socialNetwork']['twitter'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Google Plus">Google Plus</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[googlePlus]" id="googlePlus" maxlength="16" value="' . $kwm_info_options['socialNetwork']['googlePlus'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="LinkedIn">LinkedIn</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[linkedIn]" id="linkedIn" maxlength="16" value="' . $kwm_info_options['socialNetwork']['linkedIn'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';	
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Instagram">Instagram</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[instagram]" id="instagram" maxlength="16" value="' . $kwm_info_options['socialNetwork']['instagram'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';		
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Flickr">Flickr</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[flickr]" id="flickr" maxlength="16" value="' . $kwm_info_options['socialNetwork']['flickr'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';		
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="MySpace">MySpace</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[mySpace]" id="mySpace" maxlength="16" value="' . $kwm_info_options['socialNetwork']['mySpace'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';		
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Ask.fm">Ask.fm</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="text" name="socialNetwork[askfm]" id="askfm" maxlength="16" value="' . $kwm_info_options['socialNetwork']['askfm'] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';			
	$output .= '</tbody>';
$output .= '</table>';
?>