<?php
$output .= '<h2><a class="show" label="1" onclick="return false;" href="#">'.__('Phones', 'kwm_info_basic').'</a></h2>';
$output .= '<table class="hidden 1 table table-bordered table-striped" id="contact">';
	$output .= '<tbody>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="telephone1">'.__('Telephone', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="tel" name="allPhones[telephone][]" id="telephone" maxlength="16" value="' . $kwm_info_options['allPhones']['telephone'][0] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="telephone1">'.__('Telephone', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="tel" name="allPhones[telephone][]" id="telephone" maxlength="16" value="' . $kwm_info_options['allPhones']['telephone'][1] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="telephone1">'.__('Telephone', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="tel" name="allPhones[telephone][]" id="telephone" maxlength="16" value="' . $kwm_info_options['allPhones']['telephone'][2] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Celular">'.__('Cell Phone', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="tel" name="allPhones[mobile-phone][]" id="celular" maxlength="16" value="' . $kwm_info_options['allPhones']['mobile-phone'][0] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Celular">'.__('Cell Phone', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="tel" name="allPhones[mobile-phone][]" id="celular" maxlength="16" value="' . $kwm_info_options['allPhones']['mobile-phone'][1] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';
		$output .= '<tr>';
			$output .= '<th scope="row">';
				$output .= '<label for="Celular">'.__('Cell Phone', 'kwm_info_basic').'</label>';				
			$output .= '</th>';
			$output .= '<td>';
				$output .= '<input type="tel" name="allPhones[mobile-phone][]" id="celular" maxlength="16" value="' . $kwm_info_options['allPhones']['mobile-phone'][2] . '" />';
			$output .= '</td>';			
		$output .= '</tr>';			
	$output .= '</tbody>';
$output .= '</table>';
?>